# Generated by Django 5.0.6 on 2026-08-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_file_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('available', 'Available'), ('partially_available', 'Partially available'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
