# Generated by Django 5.0.6 on 2026-08-29 19:09

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('chunk_size', models.BigIntegerField(default=files.models._default_chunk_size)),
                ('replication_level', models.CharField(choices=[('standard', 'Standard'), ('safe', 'Safe'), ('maximum', 'Maximum')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('available', 'Available'), ('partially_available', 'Partially available'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('replica_number', models.PositiveIntegerField(default=0)),
                ('google_file_id', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('available', 'Available'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('upload_started_at', models.DateTimeField(blank=True, null=True)),
                ('upload_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['index', 'replica_number'],
            },
        ),
    ]
