# Generated by Django 5.0.6 on 2026-08-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('google_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='google_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='google_accounts.googleaccount'),
        ),
    ]
