# Generated by Django 5.0.6 on 2026-08-29 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filechunk',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='accounts.storageaccount'),
        ),
        migrations.AddField(
            model_name='filechunk',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='files.drivefile'),
        ),
        migrations.AddConstraint(
            model_name='filechunk',
            constraint=models.UniqueConstraint(fields=('file', 'index', 'replica_number'), name='uniq_chunk_replica'),
        ),
        migrations.AddConstraint(
            model_name='filechunk',
            constraint=models.UniqueConstraint(fields=('file', 'index', 'account'), name='uniq_chunk_account'),
        ),
    ]
