# Generated by Django 5.0.6 on 2026-08-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='categorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivefile',
            name='category',
            field=models.CharField(blank=True, choices=[('research', 'Research'), ('invoices', 'Invoices'), ('legal', 'Legal'), ('personal', 'Personal'), ('datasets', 'Datasets'), ('reports', 'Reports'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
